### ISSUE TITLE
Is the package still maintained?

### ISSUE THREAD

**Issue by cgpu** [dandermotj/MetSizeR#1]
Hi Dan,

Thanks for this metabolomics #Rstats package.
I am interested in using it, but your latest commit for the package was a while ago.

Do you intend to maintain it?
Or is anything I should be aware of before going for it, eg. WIP functions etc that you did not have the resources to implement?

The package seems really nice and I haven't found many if any similar at all.

Cheers,
Christina

**Comment by 1danjordan** [comment]
Hi @cgpu,

Sorry it's taken me so long to reply, it's been a busy few months for me. No this is not being maintained. It was an attempt by me to take a piece of code written by a PhD student that was difficult to use, and rewrite it and extend it so that it could be used more easily and widely. 

This was at the very start of my own journey becoming an R developer, so I can only imagine how poor my rewrite was. I will not be returning to this piece of code, so will archive the repo to reflect that. 

Thanks,
Dan
